### Arrays
- data structure given by Numpy
- better than arrays at huge data
- 

### Array Properties
- what attributes numpy gives you for array object

- ndim - means Dimensions - the number of axis of an array - 
- shape - number of rows, number of columns
- size - number of elements inside
- dtype - the type of array or the elements inside are of which type

In [5]:
import numpy as np

In [25]:
array1d = np.array([1,2,3,4]) # 1D array --- row of elements --- Vector ---> one axis
array1d.ndim # 1


array2d = np.array([[1, 2, 3, 4],
                    [3, 4, 5, 6]]) # 2D array  ---- 2 axis --- rows, columns
array2d.ndim # 2

array3d = np.array([[[1],[1]],
                    [[1],[1]]]) # 3D array  ----- 3 axis, ---- rows, columns, height/ depth or number of 2d arrays
array3d.ndim # 3 

3

In [26]:
array3d.shape

(2, 2, 1)

In [ ]:
array2d = np.array([[1, 2, 3, 4],
                    [3, 4, 5, 6]]) # 2D array
array2d.ndim # 2
array2d.shape # (2, 4) # rows , columns
array2d.size # 8 --- how many elements
array2d.dtype #  int64 --- type of data inside the array --- type of array

dtype('int64')

- inhomogeneous shapes are not allowed for multi-dim array
- 

##### Broadcasting

In [ ]:

num_4 = np.array([1, 2, 3, 4])
num_3 = np.array([10, 10, 20])

# multiplication with a scalar
(num_4 * 10) + 2 # like implementing an entire equation on a array

# multiplication with another array
#num_3 * num_4 # Error: operands could not be broadcast together with shapes (3,) (4,)
# the shape has to allow such an operation

array([12, 22, 32, 42])

In [ ]:
arr_table= np.array([[1, 2, 3, 4],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],
                    [3, 4, 5, 6],]) # 2D array


arr_table.ndim # 2

arr_table.shape # (10, 4) ---> 10 rows, 4 columns

(10, 4)

In [ ]:
# please take all elements and multiply them by 100
arr_table *10

# for each column different values to operate
# first column every element must be taken in 10s, 2nd --> 100s, 3rd 1000s, 4th ---> 10000

# (10, 4) --->  

arr_table * [10,100,1000,10000] # (10, 4) --- (4,) =====  10 x 4    --- 1 x 4

# mis match of shapes
# arr_table * [10,100,1000,10000,10,100,1000,10,100,1000] # (10,4) (10,)   ===== 10 x 4 ---- 1 x 10 (not possible)

arr_table * [[10],[100],[1000],[10000],[10],[100],[1000],[10],[100],[1000]]  #  (10, 4) --- (10, 1)


array([[   10,    20,    30,    40],
       [  300,   400,   500,   600],
       [ 3000,  4000,  5000,  6000],
       [30000, 40000, 50000, 60000],
       [   30,    40,    50,    60],
       [  300,   400,   500,   600],
       [ 3000,  4000,  5000,  6000],
       [   30,    40,    50,    60],
       [  300,   400,   500,   600],
       [ 3000,  4000,  5000,  6000]])

In [20]:
np.array([[10],[100],[1000],[10000],[10],[100],[1000],[10],[100],[1000]] ).shape  # (10,) ---> does not say 10 rows, it says elements

(10, 1)

### Creating an array
- ways to quickly create some arrays
- 

In [ ]:
num_list = [x for x in range(10)]

# pass list into array
arr = np.array(num_list)
arr



# use method arange()
arr = np.arange(1,10, 2) # just like range but for arrays
arr


# zeros or ones
np.zeros((3,3)) # pass a (shape) inside
np.ones((2,3))
np.ones(5)


# using linspace ---- evenly spaced values
# linearly the range you set is divided
np.linspace(0, 10, 3) # start from 0, go to 10, and break in 3 parts
# can use this to create lines --- 

array([0, 0])

In [ ]:
# create a random array

# we set the starting point using seed --- for reproducability
np.random.seed(42)  # sets the starting point of random number generator - 

np.random.randint(0, 5) # one random number between 0 to 5

np.random.randint(0, 5, 10) # 10 random number random between 0 to 5

np.random.randint(0, 5, (2,3)) # we can pass a shape we want in the end

array([[2, 4, 1],
       [3, 1, 3]])

### Slicing and Indexing

### Important array methods

### Array Multiplication

### Aggregations and Boolean Masking