In [ ]:
#pip install numpy

In [ ]:
import numpy as np

num_list = [1,2,3,4,5]
num_array = np.array(num_list)
print(num_array)

num_array

type(num_array)


In [2]:
num_list = [1, 2.0, 'idrees', 4, 5]
num_array = np.array(num_list)
num_array

NameError: name 'np' is not defined

In [4]:
num_list = [1,2,3,4,5,6,7,8,9]

result = []

for num in num_list:
    result.append(num*10)

print(result)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [5]:
num_list = [1, 2, 3, 4, 5]

for i in range(len(num_list)):
    num_list[i] *= 10

print(num_list)

[10, 20, 30, 40, 50]


In [ ]:
import numpy as np
 
num_4 = np.array([1, 2, 3, 4])
num_3 = np.array([10, 10, 20])
 
#num_3 * num_4 # Error: operands could not be broadcast together with shapes (3,) (4,)
(num_4 * 10) + 2

In [ ]:
array1d = no.array([1, 2, 3, 4])
array1d.ndim

array2d = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])
array2d.ndim

array3d = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])
array3d.ndim

In [13]:
numbers = []

for i in range(1, 5):
    numbers.append(10 ** i)

print(numbers)

[10, 100, 1000, 10000]


In [4]:
import numpy as np

img_8x8 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
 
], dtype= np.bool)

In [ ]:
from PIL import Image

img_pil = Image.fromarray(img_8x8)
img_pil = img_pil.resize((200, 200))

img_pil

In [5]:
import numpy as np

data = np.array([[2, 2, 3],
                 [20, 1, 20],
                 [3, 4, 5]])

data

row_means = data.mean(axis=1)
print(row_means)

[ 2.33333333 13.66666667  4.        ]


In [6]:
age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])
 
vote_age = age[age >= 18]
print(vote_age)

[24 51 23 29 33 44]


In [1]:
import numpy as np

# ======================================
# Scenario 1
# ======================================

# 1. Setup
np.random.seed(42)

# 2. Generate scores for 10 students and 3 subjects
scores = np.random.randint(0, 101, size=(10, 3))

print("Scores Array:")
print(scores)

# 3. Array Inspection
print("\nArray Information")
print("Dimensions (ndim):", scores.ndim)
print("Shape:", scores.shape)
print("Total Size:", scores.size)

# 4. Student IDs (100 to 109)
student_ids = np.arange(100, 110)

print("\nStudent IDs:")
print(student_ids)

# 5. Average score for each subject
subject_average = np.mean(scores, axis=0)

print("\nAverage Score Per Subject:")
print(subject_average)

# 6. Boolean Masking (scores below 50)
failing_scores = scores[scores < 50]

print("\nFailing Scores (<50):")
print(failing_scores)

# 7. Automated Grading
report_card = np.where(scores < 50, "Fail", "Pass")

print("\nReport Card:")
print(report_card)

Scores Array:
[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]

Array Information
Dimensions (ndim): 2
Shape: (10, 3)
Total Size: 30

Student IDs:
[100 101 102 103 104 105 106 107 108 109]

Average Score Per Subject:
[49.8 58.7 44.1]

Failing Scores (<50):
[14 20 23  2 21  1 29 37  1 20 32 21 48]

Report Card:
[['Pass' 'Pass' 'Fail']
 ['Pass' 'Pass' 'Fail']
 ['Pass' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Fail' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Fail']
 ['Fail' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Fail']]


In [ ]:
# ======================================
# Scenario 2
# ======================================

# 1. Numerical Data
student_ids = np.arange(101, 106)

# Example final scores for 5 students
scores = np.array([78, 45, 92, 50, 33])

# 2. Create Pass/Fail Status
status = np.where(scores >= 50, "Pass", "Fail")

# 3. Merge using column_stack
final_report = np.column_stack((student_ids, scores, status))

print("\nFinal Report:")
print(final_report)

# 4. Check data type
print("\nData Type of Final Report:")
print(final_report.dtype)

# Try adding bonus points
try:
    final_report[:, 1] = final_report[:, 1].astype(int) + 5
    print("\nAfter Adding Bonus Points:")
    print(final_report)
except Exception as e:
    print("\nError:")
    print(e)


Final Report:
[['101' '78' 'Pass']
 ['102' '45' 'Fail']
 ['103' '92' 'Pass']
 ['104' '50' 'Pass']
 ['105' '33' 'Fail']]

Data Type of Final Report:
<U21

After Adding Bonus Points:
[['101' '83' 'Pass']
 ['102' '50' 'Fail']
 ['103' '97' 'Pass']
 ['104' '55' 'Pass']
 ['105' '38' 'Fail']]
