- Numpy - numerical opeartion
- Pandas - deal with data manipulation
- Matplotlib - plotting library
- Scikit-learn - machine learning
- Tensorflow or PyTorch - are frameworks for deep learning

NumPy

- Numerical Python - Num Py
- gives us a fast data type - called Array or `ndarray`
- Numpy helps us do math on arrays
    - Data science and analysis?, how 

- numpy is one of the most fundamental libraries in python
- 

- Everthing we covered so far, was to teach you python and programming
    - is so that you can learn things on you own later

## Arrays
- Arrays is a homogenous and linear data structure
    - homogeous - you save only one type of elements inside
    - it has indicies - we can use them to access data
    - Contigous blocks of memory - every eloement comes one after the other 

- if we already have list in python, why do we need arrays?
    - Array are very `FAST` compared to list
        - reason is not just how numpy no

In [8]:
import numpy as np

num_array = np.array([1,2,3,4,5])
print(num_array)


[1 2 3 4 5]


In [ ]:
import numpy as np

num_list = [1,2,3,4,5] # python list
num_array = np.array(num_list)  # python list as argument to the  array() method
print(num_array) # [1 2 3 4 5]

num_array # array ([1,2,3,4,5])

# print(num_array) # [1 2 3 4 5]

# type(num_array) # numpy.ndarray

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
# homogenity of arrays

num_list =[1, 2.0,"idrees", 4, 5] # multipe types of data

num_array = np.array(num_list) # array will lose its special powers
# you cam create an array like this
# dtype='<U32' ---> this data type says that --- this array won't be as fast
# array will lose its spoecial power of speed and memory optimization

num_array



array(['1', '2.0', 'idrees', '4', '5'], dtype='<U32')

In [ ]:
# EXCERCISE #1_10.06.2026

num_list = [1,2,3,4,5,6,7,8,9] # [10,20,30,40,50,60,70,80,90]
num_list10 = []

num_list10 = [x * 10 for x in num_list]
print(num_list10)



[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
# EXCERCISE_Nomie's answer

num_list = [1,2,3,4,5,6,7,8,9]
 
num_list10 = [x * 10 for x in num_list]
print(num_list10)


[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
# EXCERCISE_Lindaq's answer

num_list = [1,2,3,4,5,6,7,8,9]
 
num_list10 = [num * 10 for num in num_list]
 
print(num_list10)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
num_array = np.array(num_list)
num_array # array ([1,2,3,4,5,6,7,8,9])


num_4 = ([1,2,3,4])
num_3 = np.array([10,10,20])


- This is called **BROADCASTING** 
    - one of the special things about Numpy
    - Broadcasting means taking an array and operating it with another
        - following a one to one 

List | Array
-----|------
Store pointer(address of the data)  |  Store the actual data
object are scattered through the memory  |  are Contigous (one after the other)
CPU has to go to each object address to access data  |  CPU accesses base address and eg. 8 to that address to get the next element
Heterogenous, every object of different type  |  Homogenous. Multiple types are not allowed
every object has some extra baggage like data type information |  dtype of an entire array is a same
Broadcasting is not allowed  |  Broadcasting can be done

Shapes and Dimensions

1D array:

2D array:

3D array:

In [2]:
# pip install numpy 

# EXCERCISE #2_10.06.2026



In [38]:
pylist = [100,200,300]

print(id(pylist))  # where is the pylist variable saved
print(id(pylist[0])) # locatio /address of the first element
print(id(pylist[1]))
print(id(pylist[2]))


2778673626816
140720120713432
140720120716632
2778672114224


In [39]:
pylist = [100,200,"300"]

print(id(pylist))  # where is the pylist variable saved
print(id(pylist[0])) # locatio /address of the first element
print(id(pylist[1]))
print(id(pylist[2]))

2778673544896
140720120713432
140720120716632
2778673158816


In [40]:
pylist = np.array([100,200,300])

print(id(pylist))  # where is the pylist variable saved
print(id(pylist[0])) # locatio /address of the first element
print(id(pylist[1]))
print(id(pylist[2]))

2778673851312
2778672107984
2778672114384
2778672107984


In [41]:
pylist = np.array([100,200,300], dtype = np.int64)

print(id(pylist))  # where is the pylist variable saved
print(id(pylist[0])) # locatio /address of the first element
print(id(pylist[1]))
print(id(pylist[2]))

2778673852560
2778672114480
2778672107888
2778672114480


In [42]:
np_arr = np.array([100,200,300], dtype = np.int64)
np_arr.ctypes.data # base address

2778284263952

In [43]:
id(np_arr)

2778673856304

In [50]:
np_arr[0]

np.int64(100)

In [51]:
print(id(np_arr[0]))
print(id(np_arr[1]))
print(id(np_arr[2]))
print(id(np_arr[2]))

2778672116240
2778672116304
2778672115504
2778672116304
