# to store data
# to extract data from file
 

# Panda
- python library
- fast, powerful, flexible and easy to use open source data *analysis* and *manipulation* tool
- provides series & Dataframe objects
- these objects are use to store & manipulate structures data ( data in tabular form)


- pandas comes from 'Panel Data'
- 'Python for Data Analysis' 
- s refers to the series object

In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd


In [ ]:
Core Objects

- Series - is a one dimensional labelled array (like a single column)
    - series = one column
- DataFrame - a two-dimensional table made of multiple series of same index
    - dataframe = a sheet of columns and rows

In [3]:
pd.Series([20,30,40])

0    20
1    30
2    40
dtype: int64

In [5]:
marks = pd.Series([20,30,40])
type(marks) #pandas.Series
print(marks)

0    20
1    30
2    40
dtype: int64


In [3]:
maths = pd.Series([20,30,40], dtype = 'int8', name = 'maths')
type(maths) #pandas.Series

print(maths)

0    20
1    30
2    40
Name: maths, dtype: int8


In [4]:
english = pd.Series([20,30,40])
python = pd.Series([20,55,40])
science = pd.Series([20,99,40])

In [10]:
import pandas as pd

pd.concat([maths, english, python, science]) # # series objects

df =pd.concat([maths, english, python, science], axis = 1) # dataframe

print(type(df)) #pandas.DataFrame
print(df)

<class 'pandas.DataFrame'>
   maths   0   1   2
0     20  20  20  20
1     30  30  55  99
2     40  40  40  40



DataFrame -
- column, row

In [ ]:
# dataFrame from dictionary of Lists --- each list need to be in the same size
data = {
    "Students": ['Nomie', 'Idrees', 'Radia'],
    "Maths": [85,95,90],
    "English": [75,85,80],
}
df = pd.DataFrame(data) # use this to create a dataframe from a dictionary
df # final for recall results of coding
# print(df)   
# display(df)

,Students,Maths,English
0,Nomie,85,75
1,Idrees,95,85
2,Radia,90,80


In [14]:
# dataFrame from list of dictionary --- each dictionary can be of diff size
# we can miss elements ---- those elements will appear as Nan values
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Paris'}
]
 
df = pd.DataFrame(data)
# print(df)
df

,Name,Age,City
0,Alice,25,New York
1,Bob,30,London
2,Charlie,35,Paris


NaN values
Not a Number
aka Missing Values

In [15]:
# dataframe from 2D arrays
data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'London'],
    ['Charlie', 35, 'Paris']
]

# We must explicitly define columns here
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'], )
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


Series has:

Index
Name
DataFrame will have:

Header - is the names of columns
pd.DataFrame(file, columns = ["col1", "col2", "col3"])
Index -
pd.DataFrame(file, columns = ["col1", "col2", "col3"], index = [1,2,3])
index_col = "column name" ===> argument we can pass as well
df.set_index("column name")

Mini Activity:
1. create a pd.Series with 5 temperature values & print it
2. create a pd.DataFrame with columns "City" & "Temparature" for 3 cities
3. Check the type() of each object you created
4. Add a name your Series & print it again

In [ ]:
import pandas as pd

# 1. Create a Series with 5 temperature values
temperatures = pd.Series([28, 30, 27, 31, 29])

print("Temperature Series:")
print(temperatures)

# 2. Create a DataFrame with City and Temperature columns
data = {
    "City": ['KL', 'Ipoh', 'Rawang'],
    "Temperatues": [32,30,29],
}
df = pd.DataFrame(data) # use this to create a dataframe from a dictionary
print(df)   

# 3. Check the type of each object
print("\nType of temperatures:")
print(type(temperatures))

print("\nType of weather_df:")
print(type(weather_df))

# 4. Add a name to the Series and print again
temperatures.name = "Daily Temperatures"

print("\nNamed Series:")
print(temperatures)

print("\nSeries Name:")
print(temperatures.name)

In [ ]:
# DataFrames from Files
 
# From a CSV file
df_csv = pd.read_csv('my_data.csv')
 
# From an Excel file
df_excel = pd.read_excel('my_data.xlsx')
 
# From a JSON file or API response
df_json = pd.read_json('my_data.json')

In [16]:
# Let's create a sample CSV file first, then read it
sample_data = """Name,Department,Salary,Experience
Alice,Engineering,75000,3
Bob,Marketing,65000,5
Charlie,Engineering,80000,7
Diana,HR,60000,2
Eve,Marketing,70000,4"""
 
with open('employees.csv', 'w') as f:
    f.write(sample_data)

In [17]:
import pandas as pd

df = pd.read_csv('employees.csv')
df
# display(df)

,Name,Department,Salary,Experience
0,Alice,Engineering,75000,3
1,Bob,Marketing,65000,5
2,Charlie,Engineering,80000,7
3,Diana,HR,60000,2
4,Eve,Marketing,70000,4


In [20]:
# Dataframe for the Previou Scenario Exercise

import numpy as np
np.random.seed(42)
 
#2.
results = np.random.randint(0,101, (10,3))
print("--- Results ---")
print(results)

df_results = pd.DataFrame(results, columns = ["maths", "english","science"])

df_results.to_csv("student_marks.csv", index = False) # it excludes the index

df_results

--- Results ---
[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]


,maths,english,science
0,51,92,14
1,71,60,20
2,82,86,74
3,74,87,99
4,23,2,21
5,52,1,87
6,29,37,1
7,63,59,20
8,32,75,57
9,21,88,48
