### Array Multiplication

Matrix multiplication is not regular multiplication:
- use the `@` operator like ---- A @devidrees
- use the `np.matmul( A , B )`

In [ ]:
# Matrix Multiplication

# 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [ ]:
C = A * B # element wise operation or Broadcasting
C

array([[ 5, 12],
       [21, 32]])

In [ ]:
# 2x2 matrices
A = np.array([2, 2, 3]) # row

B = np.array([[10], [10], [10]]) # column vector


print(A.shape) # 1 x 3
print(B.shape) # 3 x 1

(3,)
(3, 1)


In [ ]:
D = A @ B # Row to column --- possible
D

#E = B @ A # column to row is not
E = np.matmul(A, B)
E

array([70])

In [ ]:
# Example 3

A = np.array([[2,  2,  3],
             [20, 20, 20]]) # row ---> shape = ( 2 , 3 )

B = np.array([[2, 3],
              [3, 3],
              [5, 5]]) # column vector ---> Shape ---> ( 3 , 2 )


# 2 ,3  --- 3,2 
# is matrix multiplication possible?
A @ B


#print(A.shape) # 1 x 3
#print(B.shape) # 3 x 1

array([[ 25,  27],
       [200, 220]])

### Aggregations and Boolean Masking