### Array Multiplication

Matrix multiplication is not regular multiplication:
- use the `@` operator like ---- `A @ B`
- use the `np.matmul( A , B )`

In [1]:
import numpy as np

In [ ]:
# Matrix Multiplication

# 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [ ]:
C = A * B # element wise operation or Broadcasting
C

array([[ 5, 12],
       [21, 32]])

In [ ]:
# 2x2 matrices
A = np.array([2, 2, 3]) # row

B = np.array([[10], [10], [10]]) # column vector


print(A.shape) # 1 x 3
print(B.shape) # 3 x 1

(3,)
(3, 1)


In [ ]:
D = A @ B # Row to column --- possible
D

#E = B @ A # column to row is not
E = np.matmul(A, B)
E

array([70])

In [ ]:
# Example 3

A = np.array([[2,  2,  3],
             [20, 20, 20]]) # row ---> shape = ( 2 , 3 )

B = np.array([[2, 3],
              [3, 3],
              [5, 5]]) # column vector ---> Shape ---> ( 3 , 2 )


# 2 ,3  --- 3,2 
# is matrix multiplication possible?
A @ B


#print(A.shape) # 1 x 3
#print(B.shape) # 3 x 1

array([[ 25,  27],
       [200, 220]])

### Aggregations 
- Aggregations: - data and you summarize it 
    - Sum
    - mean
    - min max
    - Standard Deviation
    - Variance
    - count
    - argmax argmin

- Aggregation along an AXIS
- `axis = 0` ===> operate on Columns --- (down the ROWs)
- `axis = 1` ===> operate on Rows ---  (across the COLUMN)

In [31]:
data1d = np.array([2, 5, 12, 6, 7, 9])

data1d.sum()
data1d.min()
data1d.max()

data1d.argmax() # 2 ===> at 2 lies the higest number of the list
data1d.argmin() # index of the smallest number

np.int64(0)

In [ ]:
data = np.array([[2,  2,   3],
                 [20, 1,  20],
                 [ 3,  4,  5]])

# aggregations - using numpy array methods
data.sum() # add all the elements inside this array

data.mean() # mean ---> sum of all elements / number of elements ====> Average value of data

data.min() # smallest element
data.max() # largest element

data.std()
data.var()

data.argmax()
data.argmin()

data.size    # the number of elements 

9

In [53]:
print("Column-Wise sum (axis = 0)",data.sum(axis = 0)) # column wise means -- down the rows
print("Row-wise Wise sum (axis = 1)",data.sum(axis = 1)) # row wise means --- across the columns

# give me the mean of all the rows in the array
data.mean(axis = 1)

Column-Wise sum (axis = 0) [25  7 28]
Row-wise Wise sum (axis = 1) [ 7 41 12]


array([ 2.33333333, 13.66666667,  4.        ])

In [ ]:
# ways to aggregate data in python
#PYTHON
# very insufficient

data_list = [1, 2, 3, 4, 5]
data_list2d = [[2,  2,  3], [20, 20, 20]]

sum(data)  # array([22, 22, 23])

sum(data_list)  # 15 === sum of all elements

#sum(data_list2d) # unsupported by python
# mean(data) # in python mean is not any method

min(data_list)
max(data_list)
# min(data) # 2d array - python is confused

# A python method that is used, despite of numpy
# length of the iterable or sequential
len(data_list2d)

2

### Boolean Masking - (Filtering)
- used to filter elements out
- 
- array[mask] ==== mask is a condition
- `array_name[<condition>]`

In [59]:
scores = np.array([45, 71, 88, 30, 55, 90])

# broadcasting works on arrays
scores > 50  # array([False,  True,  True, False,  True,  True])
# element wise comparison

# Boolean masking
scores[scores > 50] # whereever this condition is true


# mask is just a condition
mask = scores % 2 == 0
scores[mask]

array([88, 30, 90])

In [74]:
age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])

# i only want to pass ages >= 18
vote_age = age[age >= 18]
print(vote_age)

[24 51 23 29 33 44]


In [ ]:
# np. where works with conditionals
# np.where(condition, value_if_True, value_if_False)

In [84]:
# where
age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])

voting_eligiblity = np.where(age >= 18, "Eligible", "Not-Eligible")
print(age)
print(voting_eligiblity)
print("---"*5)

zip_list = list(zip(age, voting_eligiblity))
# zip - packs two iterables of equal length together

for age, eligibility in zip(age, voting_eligiblity):
    print(f"{age} : {eligibility}")


[ 5 17 24 51 23 14  8 29 33 44 10]
['Not-Eligible' 'Not-Eligible' 'Eligible' 'Eligible' 'Eligible'
 'Not-Eligible' 'Not-Eligible' 'Eligible' 'Eligible' 'Eligible'
 'Not-Eligible']
---------------
5 : Not-Eligible
17 : Not-Eligible
24 : Eligible
51 : Eligible
23 : Eligible
14 : Not-Eligible
8 : Not-Eligible
29 : Eligible
33 : Eligible
44 : Eligible
10 : Not-Eligible


In [83]:
zip_list

[(np.int64(5), np.str_('Not-Eligible')),
 (np.int64(17), np.str_('Not-Eligible')),
 (np.int64(24), np.str_('Eligible')),
 (np.int64(51), np.str_('Eligible')),
 (np.int64(23), np.str_('Eligible')),
 (np.int64(14), np.str_('Not-Eligible')),
 (np.int64(8), np.str_('Not-Eligible')),
 (np.int64(29), np.str_('Eligible')),
 (np.int64(33), np.str_('Eligible')),
 (np.int64(44), np.str_('Eligible')),
 (np.int64(10), np.str_('Not-Eligible'))]

In [82]:
# column stack combines two arrays of equal length

age = np.array([5,17,24, 51, 23, 14, 8, 29, 33, 44, 10])
voting_eligiblity = np.where(age >= 18, "Eligible", "Not-Eligible")

combined_array = np.column_stack((age, voting_eligiblity))
combined_array

array([['5', 'Not-Eligible'],
       ['17', 'Not-Eligible'],
       ['24', 'Eligible'],
       ['51', 'Eligible'],
       ['23', 'Eligible'],
       ['14', 'Not-Eligible'],
       ['8', 'Not-Eligible'],
       ['29', 'Eligible'],
       ['33', 'Eligible'],
       ['44', 'Eligible'],
       ['10', 'Not-Eligible']], dtype='<U21')