## NEURAL NETWORKS (NN)
- how they work in code
- try to implement iris classification using NN
- data is too less for great DL results, but the process will be demonstatred
- along the way


# General Process:
1. Build the Network
2. 
3. 
4. 
5. 
6. Repeat

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
pip install numpy pandas matplotlib seaborn scikit-learn tensorflow

  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 5.6 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.2 MB 5.0 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.2 MB 5.9 MB/s eta 0:00:01
   ---------------------- ----------------- 4.7/8.2 MB 5.8 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 5.7 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 5.4 MB/s  0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
   -------------------

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
 
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
# bring the data
 
iris = load_iris()
 
X, y = iris.data, iris.target
 
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 4) (38, 4) (112,) (38,)


In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# Model

model = keras.Sequential([
    # input layer : no neurons, just a placeholder for innput
    layers.Input(shape = (4,)),

    # hidden layer : 
    layers.Dense(units = 5, activation = "relu"),

    #output layer : 
    layers.Dense(units = 3, activation = "softmax")
])


# model compilation - compile the model
model.compile(
    optimizer = 'adam', # optimzer in gradient descent which helps model to redduce the error to fnd least possible error - Global Minima
    loss = 'sparse_categorical_crossentropy', # function used to calculate the loss, most common sparse_categorical_crossentropy (multiclass & integer label) & categorical crossentropy
    metrics = ['accuracy']
)

In [7]:
# Training

model.fit(X_train, y_train,
epochs = 100,
batch_size = 10,
validation_split = 0.3
)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.3462 - loss: 1.1457 - val_accuracy: 0.2647 - val_loss: 1.1891
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3462 - loss: 1.1184 - val_accuracy: 0.2647 - val_loss: 1.1549
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3974 - loss: 1.0949 - val_accuracy: 0.3529 - val_loss: 1.1268
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 1.0751 - val_accuracy: 0.3824 - val_loss: 1.1041
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5513 - loss: 1.0592 - val_accuracy: 0.4412 - val_loss: 1.0882
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6154 - loss: 1.0487 - val_accuracy: 0.4706 - val_loss: 1.0738
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6410 - loss: 1.0395 - val_accuracy: 0.5882 - val_loss: 1.0627
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6538 - loss: 1.0317 - val_accuracy: 0.5882 - val_loss: 1.05

In [8]:
# Evaluation

predictions = model.predict(X_test)
predictions.round(2)

# confidence of each cateogry
# prediction is made by taking highest value



2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[0.04, 0.41, 0.55],
       [0.03, 0.4 , 0.57],
       [0.91, 0.06, 0.03],
       [0.9 , 0.07, 0.03],
       [0.02, 0.37, 0.6 ],
       [0.07, 0.43, 0.49],
       [0.04, 0.42, 0.54],
       [0.93, 0.05, 0.02],
       [0.05, 0.43, 0.51],
       [0.02, 0.36, 0.62],
       [0.04, 0.42, 0.54],
       [0.93, 0.05, 0.02],
       [0.92, 0.05, 0.03],
       [0.03, 0.4 , 0.57],
       [0.03, 0.39, 0.59],
       [0.96, 0.03, 0.01],
       [0.1 , 0.46, 0.44],
       [0.86, 0.1 , 0.05],
       [0.11, 0.43, 0.46],
       [0.94, 0.04, 0.02],
       [0.09, 0.44, 0.47],
       [0.88, 0.08, 0.04],
       [0.03, 0.39, 0.59],
       [0.92, 0.05, 0.03],
       [0.06, 0.45, 0.49],
       [0.91, 0.06, 0.03],
       [0.93, 0.05, 0.02],
       [0.03, 0.39, 0.59],
       [0.04, 0.42, 0.54],
       [0.02, 0.36, 0.62],
       [0.1 , 0.45, 0.46],
       [0.02, 0.38, 0.6 ],
       [0.1 , 0.45, 0.44],
       [0.08, 0.44, 0.48],
       [0.03, 0.41, 0.56],
       [0.04, 0.41, 0.55],
       [0.8 , 0.13, 0.07],
 

In [9]:
y_pred = np.argmax(predictions, axis = 1) # the index of the highest value from each row
y_pred

array([2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 1, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 0])

In [10]:
# to see the outputs
for i in range(len(predictions)): 
    print(f"Predicted Class: {np.argmax(predictions[i])} | Actual: {y_test[i]}")

Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 2
Predicted Class: 0 | Actual: 0
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 1
Predicted Class: 2 | Actual: 2
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 1
Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 1
Predicted Class: 0 | Actual: 0
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 2
Predicted Class: 0 | Actual: 0
Predicted Class: 1 | Actual: 1
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 1
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 1
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 2
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 1
Predicted Class: 0 | Actual: 0
Predicted Class: 0 | Actual: 0
Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 2
Predicted Class: 2 | Actual: 1
Predicted Class: 2 | Actual: 2
Predicte